2020-09-24 13:32:02,595 21490 INFO ? odoo: Odoo version 13.0 
2020-09-24 13:32:02,597 21490 INFO ? odoo: Using configuration file at /etc/odoo13_demo.conf 
2020-09-24 13:32:02,597 21490 INFO ? odoo: addons paths: ['/opt/buhaleeba/odoo13_demo/odoo/addons', '/home/ubuntu/.local/share/Odoo/addons/13.0', '/opt/buhaleeba/odoo13_demo/addons', '/opt/buhaleeba/odoo13_demo/custom/addons'] 
2020-09-24 13:32:02,598 21490 INFO ? odoo: database: buhaleeba@default:default 
2020-09-24 13:32:03,424 21490 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2020-09-24 13:32:03,672 21490 INFO ? odoo.service.server: HTTP service (werkzeug) running on ip-172-31-28-6.us-east-2.compute.internal:9013 
2020-09-24 13:35:15,882 21645 INFO ? odoo: Odoo version 13.0 
2020-09-24 13:35:15,883 21645 INFO ? odoo: Using configuration file at /etc/odoo13_demo.conf 
2020-09-24 13:35:15,883 21645 INFO ? odoo: addons paths: ['/opt/buhaleeba/odoo13_demo/odoo/addons', '/home/ubuntu/.local/share/Odoo/addons/13.0', '/opt/buhaleeba/odoo13_demo/addons', '/opt/buhaleeba/odoo13_demo/custom/addons'] 
2020-09-24 13:35:15,884 21645 INFO ? odoo: database: buhaleeba@default:default 
2020-09-24 13:35:16,754 21645 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2020-09-24 13:35:16,952 21645 INFO ? odoo.service.server: HTTP service (werkzeug) running on ip-172-31-28-6.us-east-2.compute.internal:9013 
2020-09-24 13:36:48,191 21762 INFO ? odoo: Odoo version 13.0 
2020-09-24 13:36:48,192 21762 INFO ? odoo: Using configuration file at /etc/odoo13_demo.conf 
2020-09-24 13:36:48,192 21762 INFO ? odoo: addons paths: ['/opt/buhaleeba/odoo13_demo/odoo/addons', '/home/ubuntu/.local/share/Odoo/addons/13.0', '/opt/buhaleeba/odoo13_demo/addons', '/opt/buhaleeba/odoo13_demo/custom/addons'] 
2020-09-24 13:36:48,193 21762 INFO ? odoo: database: buhaleeba@default:default 
2020-09-24 13:36:49,012 21762 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2020-09-24 13:36:49,230 21762 INFO ? odoo.service.server: HTTP service (werkzeug) running on ip-172-31-28-6.us-east-2.compute.internal:6602 
2020-09-24 13:36:56,941 21762 INFO ? odoo.http: HTTP Configuring static files 
2020-09-24 13:36:56,953 21762 INFO ? odoo.sql_db: Connection to the database failed 
2020-09-24 13:36:56,958 21762 INFO ? werkzeug: 27.7.216.60 - - [24/Sep/2020 13:36:56] "GET / HTTP/1.1" 500 - 0 0.000 0.010
2020-09-24 13:36:56,964 21762 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1421, in dispatch
    self.setup_db(httprequest)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1344, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1506, in db_monodb
    dbs = db_list(True, httprequest)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1473, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/db.py", line 378, in list_dbs
    with closing(db.cursor()) as cr:
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 654, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 191, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 537, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 605, in borrow
    **connection_info)
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  Peer authentication failed for user "buhaleeba" - - -
2020-09-24 13:36:58,129 21762 INFO ? odoo.sql_db: Connection to the database failed 
2020-09-24 13:36:58,132 21762 INFO ? werkzeug: 27.7.216.60 - - [24/Sep/2020 13:36:58] "GET /favicon.ico HTTP/1.1" 500 - 0 0.000 0.007
2020-09-24 13:36:58,137 21762 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1421, in dispatch
    self.setup_db(httprequest)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1344, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1506, in db_monodb
    dbs = db_list(True, httprequest)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1473, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/db.py", line 378, in list_dbs
    with closing(db.cursor()) as cr:
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 654, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 191, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 537, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 605, in borrow
    **connection_info)
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  Peer authentication failed for user "buhaleeba" - - -
2020-09-24 13:37:06,612 21762 INFO ? odoo.sql_db: Connection to the database failed 
2020-09-24 13:37:06,616 21762 INFO ? werkzeug: 27.7.216.60 - - [24/Sep/2020 13:37:06] "GET / HTTP/1.1" 500 - 0 0.000 0.007
2020-09-24 13:37:06,620 21762 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/server.py", line 439, in app
    return self.app(e, s)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/wsgi_server.py", line 142, in application
    return application_unproxied(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1287, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1257, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 766, in __call__
    return self.app(environ, start_response)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1421, in dispatch
    self.setup_db(httprequest)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1344, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1506, in db_monodb
    dbs = db_list(True, httprequest)
  File "/opt/buhaleeba/odoo13_demo/odoo/http.py", line 1473, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "/opt/buhaleeba/odoo13_demo/odoo/service/db.py", line 378, in list_dbs
    with closing(db.cursor()) as cr:
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 654, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 191, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 537, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/buhaleeba/odoo13_demo/odoo/sql_db.py", line 605, in borrow
    **connection_info)
  File "/opt/buhaleeba/odoo13-venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  Peer authentication failed for user "buhaleeba" - - -
